services:
  nginx:
    image: syafa/praktikum-paw:latest-nginx-bab8
    restart: always
    container_name: nginx-php
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - .:/var/www/html

  php:
    image: syafa/praktikum-paw:latest-php-bab8
    restart: always
    container_name: php
    env_file: .env
    volumes:
      - .:/var/www/html
