server {
    listen 80;
    root /var/www/html;
    index index.php index.html proses.php *.php;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #location ~ \.php$ {
    #    try_files $uri =404;
    #    fastcgi_pass php:9000;
    #    include fastcgi_params;
    #    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #}

    location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        #fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}
